apiVersion: apps/v1
kind: Deployment
metadata:
  name: knidianmd
spec:
  replicas: 2
  selector:
    matchLabels:
      app: knidianmd
  template:
    metadata:
      labels:
        app: knidianmd
    spec:
      containers:
      - name: knidianmd
        image: gcr.io/knidianmd-cicd/myapp:v1
        ports:
        - containerPort: 5000